### ISSUE TITLE
misplaced uctodata warning for tokconfig-generic configuration

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/ucto#12]
On ucto 0.9.3 **with uctodata 0.2**, and also reproduces on unreleased ucto 0.9.4:

```
configfile = tokconfig-generic
inputfile =
outputfile =
Initiating tokeniser...
skipping META rule: 'NUMBER-ORDINAL'
skipping META rule: 'ABBREVIATION-KNOWN'
skipping META rule: 'WORD-TOKEN'
skipping META rule: 'PREFIX'
skipping META rule: 'SUFFIX'
WARNING: your datafile seems out of date!
         for best results, you should use uctodata version >=0.2
```

**Comment by kosloot** [comment]
Hmm, yes. This is a harmless warning, but indeed....
ucto checks the version information in **each** datafile (tokconfig-*)
In fact there is only a weak relation between this version and the uctodata release version.
There is NO requirement that every data file has the same version. In fact after each update/edit in the data file , the version should be incremented. (which helps understanding bug reports)
So the warning is a bit off too.
The version numbers are added in the git repro, and the warning will be made more specific.

**Comment by kosloot** [comment]
Ok this is fixed in uctodata (adding version numbers)
The warning is improved too in te language0detect branch, soon t be merged into master
