### ISSUE TITLE
Refactor `Setting::read`

### ISSUE THREAD

**Issue by sanmai-NL** [LanguageMachines/ucto#14]
[This variable](https://github.com/LanguageMachines/ucto/blob/6611978c81d651f079ac99f421246d98b7ecd8c5/src/setting.cxx#L520) is only used once, in a ~much~ narrower scope.
~[This variable](https://github.com/LanguageMachines/ucto/blob/6611978c81d651f079ac99f421246d98b7ecd8c5/src/setting.cxx#L521) is written to and read from in a place while uninitialized.~

The whole method is quite lengthy and complicated, and could be decomposed. Do you need help with any of this?

**Comment by kosloot** [comment]
Sure the method is a bit lengthy and convoluted. But that is not uncommon :)
At the moment it works and there are other priorities.

Considering the variables:
- vector<string> meta_rules;
A default constructor for vector<string> is called here. So how on earth can the variable ever be uninitialized?
- int rule_count = 0;
This could indeed be moved inside the if ( f) block, a few lines below. But that is not a 'much narrower scope', just a bit narrower.
Are these 'errors' detected with CPPCHECK ?

**Comment by sanmai-NL** [comment]
[CppCheck's output](https://travis-ci.org/LanguageMachines/ucto/jobs/192135384).
As you see, it's quite moderate. It doesn't suggest your code has _errors_. [CppCheck's home](http://cppcheck.sourceforge.net/) page suggests they agressively avoid false positives.

You're right, `meta_rules` gets [default-initialized](http://en.cppreference.com/w/cpp/language/default_initialization) even in the absence of an initializer, that's C++. That was my oversight (not having programmed in C++ for a while). 

The big deal of all this it that improving the maintainability of the code will make it generally clearer and invite contributions.

**Comment by kosloot** [comment]
Improving the maintainability of the code is a good thing™ of course.
once in a while i take some time to haphazardly do so on one off the modules.
scan-build and CPPCHECK will be helpful for sure.
But we (mostly I) have >100.000 LOC at hand, and other priorities too. :{
