### ISSUE TITLE
Date tagging can be improved

### ISSUE THREAD

**Issue by sanmai-NL** [LanguageMachines/ucto#16]
# Context

## Versions
```
Ucto - Unicode Tokenizer - version 0.9.5
(c) ILK 2009 - 2014, Induction of Linguistic Knowledge Research Group, Tilburg University
Licensed under the GNU General Public License v3
based on [libfolia 1.6]
```

## Input
```
19 mei 2014
19.05.2014
19-05-2014
19-05-'14
19-5-'14
19 mei '14
```

## Invocation

```sh
ucto -X -m uctotest.txt out.xml
```
# Expected

All are recognized as dates.

# Actual

Only ‘19-05-2014’ is recognized as a date.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="folia.xsl"?>
<FoLiA xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://ilk.uvt.nl/folia" xml:id="untitleddoc" generator="libfolia-v1.6" version="1.4.0">
  <metadata type="native">
    <annotations>
      <token-annotation annotator="ucto" annotatortype="auto" datetime="2017-01-15T16:45:12" set="tokconfig-generic"/>
    </annotations>
    <meta id="language">default</meta>
  </metadata>
  <text xml:id="untitleddoc.text">
    <p xml:id="untitleddoc.p.1">
      <t>19 mei 2014 19.05.2014 19-05-2014 19-05-'14 19-5-'14 19 mei '14</t>
      <s xml:id="untitleddoc.p.1.s.1">
        <t>19 mei 2014</t>
        <w xml:id="untitleddoc.p.1.s.1.w.1" class="NUMBER">
          <t>19</t>
        </w>
        <w xml:id="untitleddoc.p.1.s.1.w.2" class="WORD">
          <t>mei</t>
        </w>
        <w xml:id="untitleddoc.p.1.s.1.w.3" class="NUMBER">
          <t>2014</t>
        </w>
      </s>
      <s xml:id="untitleddoc.p.1.s.2">
        <t>19.05.2014</t>
        <w xml:id="untitleddoc.p.1.s.2.w.1" class="NUMBER">
          <t>19.05.2014</t>
        </w>
      </s>
      <s xml:id="untitleddoc.p.1.s.3">
        <t>19-05-2014</t>
        <w xml:id="untitleddoc.p.1.s.3.w.1" class="DATE">
          <t>19-05-2014</t>
        </w>
      </s>
      <s xml:id="untitleddoc.p.1.s.4">
        <t>19-05-'14</t>
        <w xml:id="untitleddoc.p.1.s.4.w.1" class="NUMBER" space="no">
          <t>19</t>
        </w>
        <w xml:id="untitleddoc.p.1.s.4.w.2" class="NUMBER" space="no">
          <t>-05</t>
        </w>
        <w xml:id="untitleddoc.p.1.s.4.w.3" class="PUNCTUATION" space="no">
          <t>-</t>
        </w>
        <w xml:id="untitleddoc.p.1.s.4.w.4" class="NUMBER-YEAR">
          <t>'14</t>
        </w>
      </s>
      <s xml:id="untitleddoc.p.1.s.5">
        <t>19-5-'14</t>
        <w xml:id="untitleddoc.p.1.s.5.w.1" class="NUMBER" space="no">
          <t>19</t>
        </w>
        <w xml:id="untitleddoc.p.1.s.5.w.2" class="NUMBER" space="no">
          <t>-5</t>
        </w>
        <w xml:id="untitleddoc.p.1.s.5.w.3" class="PUNCTUATION" space="no">
          <t>-</t>
        </w>
        <w xml:id="untitleddoc.p.1.s.5.w.4" class="NUMBER-YEAR">
          <t>'14</t>
        </w>
      </s>
      <s xml:id="untitleddoc.p.1.s.6">
        <t>19 mei '14</t>
        <w xml:id="untitleddoc.p.1.s.6.w.1" class="NUMBER">
          <t>19</t>
        </w>
        <w xml:id="untitleddoc.p.1.s.6.w.2" class="WORD">
          <t>mei</t>
        </w>
        <w xml:id="untitleddoc.p.1.s.6.w.3" class="NUMBER-YEAR">
          <t>'14</t>
        </w>
      </s>
    </p>
  </text>
</FoLiA>
```

**Comment by sanmai-NL** [comment]
State of the art in temporal expression tagging, I believe: https://github.com/HeidelTime/heideltime.

**Comment by proycon** [comment]
The current date detection regular expression is indeed fairly simplistic: ``\p{N}{1,2}[/\-]\p{N}{1,2}[/-]\p{N}{2,4}``.  This is the generic rule used in your example, the rule differs per language generally. Dutch only does hyphens, US english does slashes, german does periods, etc..  If you have a custom situation it is of course always possible to adapt the regular expression. Allowing shorthand years like '14 might be an idea.

However, ucto is just a tokeniser and is limited at that; it won't detect dates spread over multiple tokens (19 mei 2014, three tokens, an inherent limitation in ucto prevents it from ever considering things with spaces as a single token). This would be best solved in a dedicated temporal expression tagging phase after tokenisation (so out of the scope of ucto).

**Comment by sanmai-NL** [comment]
I fully agree on your last point. Since dates are so often multi-word, I think, would it be better to remove this kind of tagging from `ucto` in order to simplify it? At least user expectations about the degree of temporal expression tagging could be tempered by clarifying/limiting the wording [here](https://github.com/LanguageMachines/ucto/blame/master/README.md#L34)?

The ‘year’ shorthands are interesting, since I found them a lot in a real-world Dutch-spoken texts. The dot separator is dispreferred for Dutch, as it's not a [standard](https://en.wikipedia.org/wiki/ISO_8601) separator, but it's not only common in German but also in Dutch-spoken texts.

**Comment by proycon** [comment]
Agreed, I reworded it a bit now.  A full temporal expression tagging tool would be a fun project by the way ;)

The shorthand years do occur a lot yes, often even on their own without day/month context, that's why we do have the "NUMBER-YEAR" rule for dutch that should currently already be triggered for those. It's a bit rarer to see it in ``dd-mm-'yy`` form I guess but I don't see much harm in adding that to the dutch regular expression possibly.

**Comment by kosloot** [comment]
To summarize:
- The Regular expression for dutch could be extended a bit to catch more weird or non-standard cases 
looking at the English variant in **uctodata** might be a starting point: 
DATE=\p{N}{1,2}/\p{Ps}?\p{N}{1,2}[/]\p{Ps}?\p{N}{2,4}
The Turkish version expects dots, but also take ' in account:
DATE=\p{N}{1,2}\.\p{N}{1,2}\.\p{N}{2,4}(?:['`’‘´-]\p{L}+)+
A merger might do the trick.
- Dates like '10 maart 2016' are beyond the scope of tokenizing with ucto. That should be solved in a higher level module. Just like other Entity recognizing (Named Entities, Multiword Units)
 Heideltime might be a solution.

remark: Tokenizing can never be 100% perfect. In my opinion, Ucto just should aim at high precision, not at full coverage of corner cases with the risk of overshooting.
it is the task of more intelligent modules: Taggers, Parsers, Heideltime etc. to add more complexity.

**Comment by sanmai-NL** [comment]
Thanks @kosloot.

**Comment by kosloot** [comment]
you're welcome :)
