### ISSUE TITLE
Manual is outdated

### ISSUE THREAD

**Issue by kosloot** [LanguageMachines/ucto#2]
We really should document new features like the meta rules.

**Comment by proycon** [comment]
Documentation now automatically deploys on: https://ucto.readthedocs.io/

**Comment by proycon** [comment]
Once the new documentation is finished, I suggest we remove the old one from this git repo, and remove references to it from the ucto website.

**Comment by proycon** [comment]
@Irishx  I just reviewed and edited the documentation

**Comment by proycon** [comment]
(We should do a new ucto release when this is finalised and ucto is up for it)

**Comment by kosloot** [comment]
A new version was released, including the enhanced manual.
Closing this issue.
