### ISSUE TITLE
Ucto crashes on overly long word strings

### ISSUE THREAD

**Issue by martinreynaert** [LanguageMachines/ucto#20]
[2]+  Segmentation fault      nohup /exp/sloot/usr/local/bin/ucto -m -n --normalize=CURRENCY,DATE,DATE-REVERSE,E-MAIL,FRACNUMBER,NUMBER,NUMBER-COMPOUND,NUMBER-ORDINAL,NUMBER-STRING,NUMBER-YEAR,PUNCTUATION,PUNCTUATION-MULTI,QUOTE-COMPOUND,REVERSE-SMILEY,SMILEY,TIME,URL,URL-DOMAIN,URL-WWW --filterpunct lol.longest.txt > lol.longest.stdout 2> lol.longest.stderr
mre@black:/opensonar/SoNaRCurated/OUT2$

Tried to process SoNaR-500 text in this fashion. Ucto crashed. Problem reduced to this very long line of '::lol::' (x 13106).

**Comment by kosloot** [comment]
remark 1: 
I suggest to select a LANGUAGE when using Frog. The default tokenizer is rather simple.
Most of the patterns mentioned in --normalize are even not defined in the default mde.

So specify -Lnld for Dutch

Remark 2:
Please attach the offensive input file. 
Or be more clear about its content.
Is it a long list of ::lol:: words separated by spaces, or just one long 'word'  like:
::lol::::lo::::lol::::lol::...

please clarify

**Comment by kosloot** [comment]
Implemented a simple safeguard. Tokens of over 2500 characters are no longer accepted. The inputline is skipped.

**Comment by kosloot** [comment]
It would be helpful to get more information about the error. A line number and an (excerpt of) the offensive token. In case of FoLiA input an id.

**Comment by kosloot** [comment]
The error message is improved now. But line-number /ID information is a bit harder to achieve.

**Comment by kosloot** [comment]
The message seems satisfying now.
