### ISSUE TITLE
Unable to load shared libraries

### ISSUE THREAD

**Issue by limogin** [LanguageMachines/ucto#21]
I compile source code 

$ bash bootstrap.sh 
$ ./configure && make && make install 

Previously I have installed libfolia from source. When we I try to call the ucto

$ ucto 
/usr/local/bin/ucto: error while loading shared libraries: libfolia.so.6:

My system is Ubuntu Server 16.04 LTS

**Comment by kosloot** [comment]
hello,
Did 'make install' for libfolia work correctly? 
You might need 'sudo' to to this. 
Otherwise you need to specify an alternative location like ~/usr/local: in ./configure
./configure --prefix=~/usr/local
You should use the same prefix for ALL our tools (ticcutils, libfolia, ucto...)

**Comment by kosloot** [comment]
additionally you might try two simple checks:
- make check
- make installcheck

The first will see if things work OK
The second will also check if the installation went correctly

**Comment by kosloot** [comment]
closing because of lack on reaction
