### ISSUE TITLE
Feature request: Rule type applied prior to whitespace tokenization, to allow protecting token sequences

### ISSUE THREAD

**Issue by etashru** [LanguageMachines/ucto#24]
I'm trying to protect token sequences enclosed in tags, e.g. `<PER>John Smith</PER>`. This is easily covered by the following regex:

`\<.*?\>[\w\s]+?\<\/.*?\>` (where `\w\s` may be `.` , if it also matches whitespace)

However, this appears to be impossible due to the fact that before considering any rules, the tokenizer splits on whitespaces. Would it be possible to add a type of rules that are evaluated prior to whitespace tokenization? Otherwise, token sequences that should be kept together have to be concatenated using special characters, reconstructed after tokenization or substituted with placeholders prior to tokenization, all of which cause overhead.

**Comment by kosloot** [comment]
You are right. Ucto basically relies on whitespace as the 'certain' token separator. Changing this would mean a major change or even need a complete rewrite. At this stage that is a no-go.
You could however make rules to 'detect' start-tags and end-tags, making post-processing more easy.
Maybe @proycon has additional ideas?

**Comment by proycon** [comment]
The forced splitting on whitespaces in ucto is indeed an unfortunate design choice that should ideally be revised at some point in the future. However, this is not an easy task, as Ko already stated.
