### ISSUE TITLE
Ucto fails to tokenise certain folia input?

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/ucto#25]
Unexpected failure in tokenisation due to clashing text content elements. Input document is ``/vol/tensusers/proycon/_gen001gent01_01.folia.xml``.

```
Command error:                                                
  ucto: --filter=NO is automaticly set. inputclass equals outputclass!                                                      
  ucto: inputfile = _gen001gent01_01.folia.xml                
  ucto: outputfile = _gen001gent01_01.tok.folia.xml           
  ucto:tokconfig-nld: version=0.2                             
  ucto: XML error: attempt to add <t> with class=current and text 'De Zuidelijke Nederlanden in de zestiende eeuw en de     
  negentien kamers die deelnamen aan het Gentse rederijkersfeest van                                                        
  1539.' to element: _gen001gent01_01.TEI.2.text.body.div.div.p.418.s.1 with parent _gen001gent01_01.TEI.2.text.body.div.div.p.418 which already has a <t> with that class and text: 'De Zuidelijke Nederlanden in de zestiende eeuw en de              
                                         negentien kamers die deelnamen aan het Gentse rederijkersfeest van                 
                                         1539.' 
```

**Comment by kosloot** [comment]
This is quite hard.
The document contains TAB characters, which are transparent to ucto.
So after tokenization, the Word, nor the Sentences, contain TAB's.
But this implies that the recomposed paragraph text (from lower levels) doesn't match the original one.

Adding TAB's in text elements is a desperate and useless attempt to retain formatting. 
A workaround would be to have teiExtractText to remove all TAB's. But this would not prevent having the same problem in other situations.
What to do..?

1. Forbid TABS in FoLiA
2. Make the FoLiA text checking mechanism transparent for TAB
3. Let ucto handle TAB's in FoLiA just like it does with NewLine. For NewLine a \<br/\> tag is inserted.
   For TAB we would then need a \<tab/\> like tag or such. 
4. totally rewrite ucto to retain all whitespace as special tokens and have some method/module to extract 'the right thing'
5. some cunning plan

Discussion:
1. Not feasible
2. doable, but hackery
3. Do we really want an extra \<tab/\> tag? 
4. A lot of work and rethinking is needed
5. I don't have it right now

**Comment by proycon** [comment]
Right, well found! This is indeed an interesting issue that we never really considered yet. In this particular case, it seems it was like this in the original TEI document and has been transferred to FoLiA with all the inline tabs. 

1. No indeed, we don't want to forbid them. It happens in practice as we've seen.
2. This seems the best solution; but it indeed shouldn't be too hackery and follow a more generic principle. This goes to the core of the whole text checking discussion in general which we never entirely finished yet. (proycon/folia#24 and LanguageMachines/libfolia#9 ). I'm thinking it may be best to make text checking fairly flexible, i.e. not too strict,  when it comes to whitespace: A tab can then treated just like a space, and multiple spaces just like a single space. 
3. No, we don't want a ``<tab/>``, it's pseudo-structure with no clear semantics where better structural elements exists.
4. Some sort of rewrite is desireable (see issue #24), but not for tabs and putting tabs in tokens.
5. See 2 ;)

**Comment by kosloot** [comment]
Ok, 2. seems to be feasible for the near future. (has impact on libfolia and folia.py)
4. is something to think and discus about later. Multiword/Split problems arise everywhere...

**Comment by kosloot** [comment]
A 'normalized' text check is implemented in libfolia (for document \>= version1.5) and seems to work well.
Ucto had already been expanded to detect newlines and replace those by \<br/\> nodes.
Although that might make sense, it is not strictly needed anymore with the new relaxed checking.
Removing this feature simplifies ucto, and doesn't hurt a lot. Keeping it does no real harm either,
so what to do...

**Comment by kosloot** [comment]
The feature to detect newlines an replace them by \<br/\> nodes is disabled for now.
It has a lot of unforeseen complications.
We really have to think very good how to handle both \n and \<br/\> (and combinations) in text.
So ucto is back to a quite numb scenario:
All whitespace, including \<br/\> is neglected.
