### ISSUE TITLE
unsupported language 'eng'

### ISSUE THREAD

**Issue by emanjavacas** [LanguageMachines/ucto#27]
I've installed ucto following the manual instructions. I also installed uctodata. I used the prefix /usr/local for all dependencies, including ucto and uctodata itself.

When I run ucto I get

```
ucto: unsupported language 'eng'
ucto: Available Languages: 
```

Any clues?

best

**Comment by kosloot** [comment]
this may very well be related to #26 
Please let us know if solving #26 didn't solve this problem

**Comment by emanjavacas** [comment]
Indeed!
