### ISSUE TITLE
Handling of abbreviations followed by punctuation goes awry

### ISSUE THREAD

**Issue by mhkuu** [LanguageMachines/ucto#3]
Ucto does great overall, but it seems to have some trouble with abbreviations before other punctuation:

`Wil je mij er even langs laten a.j.b., ik heb haast.`
`In het interview zei hij o.a.: "Ucto is cool."`

With the standard `tokconfig-nl` this leads to more sentence splits than necessary.

**Comment by kosloot** [comment]
Fixed by modifying  ABBREVIATION rule in tokconfig-nl

ABBREVIATION=^(\p{L}{1,3}(?:\.\p{L}{1,3})+\.?)(?:\Z|[,:;])
