### ISSUE TITLE
Ucto does not use folia file extension to automatically assume folia input 

### ISSUE THREAD

**Issue by fkunneman** [LanguageMachines/ucto#30]
It could be more intuitive if the input type of a file is automatically corresponding to the extension, at least in the case of folia input.

**Comment by kosloot** [comment]
the extension being .xml, .XML or..?
What to do in the odd case we want to tokenize a non-folia .xml file?
or just an XML file? (although that seems pointless)

**Comment by proycon** [comment]
``.xml`` yeah (forced to lowercase). Tokenising an XML file raw is pointless indeed, don't think that's valid to concern ourselves with.

**Comment by fkunneman** [comment]
Maybe restrict this service for files with the extension ‘folia.xml’ (either capitalized or not).

**Comment by kosloot** [comment]
1. @proycon : do you mean accepting .xml, .XML, .Xml, .xml etc? or only .xml
2. @fkunneman and @proycon : .folia.xml is a 'de-facto' standard (used by Piccl and such)
so it is tempting to restrict to that. But I would favor to accept ALL (and only?) .xml.

ucto wil have a hard time handling non-folia XML though, we might check that too.

**Comment by kosloot** [comment]
implemented:
automatically switch to -F or -X when input or outputfile have '.xml' extension(s)
