### ISSUE TITLE
Add option for outputting text (t) on deepest level (w) only

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/ucto#31]
Text redundancy is not always needed, add an option to render text output only at the deepest level (w by definition since it's a tokeniser).

**Comment by kosloot** [comment]
seems reasonable, and easy to do

**Comment by kosloot** [comment]
I added a --noredundanttext option to ucto.
a better name is welcome
please test!

**Comment by proycon** [comment]
Test seems to work fine.

**Comment by kosloot** [comment]
One important remark about this option:
When an incoming FoLiA already has some text on \<p\> or \<s\> nodes this text is left 'as-is' AND
from FoLiA v1.5 text compatibility rules will be enforced. (the normalized deeper text must equal the normalized text of the nodes)
We could decide on REMOVING the text on \<p\> or \<s\> nodes on the fly....

**Comment by proycon** [comment]
Perhaps change it into ``--textredundancy``/``-T`` parameter that takes one of three modes?

* ``full`` - Add full text redundancy (currently the default)
* ``minimal`` - Do not introduce extra redundancy, but do not remove any input text
* ``none`` - No text redundancy (actively strip and only keep the deepest level (w by definition)  

I'd also propose changing the default to minimal then. Full text redundancy is not necessary.

**Comment by kosloot** [comment]
OK, this seems very reasonable.
This option is now implemented. But with a default of 'full' for now, because i want to investigate the impact of changing that first.

**Comment by proycon** [comment]
Is this option accessible already from the frog configuration?

**Comment by kosloot** [comment]
no.
I assume this is a wish :P

**Comment by proycon** [comment]
yep ;)

**Comment by kosloot** [comment]
your wish is our command. So a -T / --textredundancy option is added now.
Also the default is set to 'minimal'
