### ISSUE TITLE
Difficulties with complex <t> contents

### ISSUE THREAD

**Issue by JessedeDoes** [LanguageMachines/ucto#34]
Some (not always very meaningful) internally complex t-elements give problems.

Typical exception:
ucto: no such text: s::textcontent(default)

Example:

[voorbeeld_NoSuchText.xml.txt](https://github.com/LanguageMachines/ucto/files/1369482/voorbeeld_NoSuchText.xml.txt)

&lt;head xml:id="TEI.1.text.1.front.1.div1.4.head.1">&lt;t class="default">&lt;t-style class="italic">Op zijnen&lt;/t-style> YSTROOM.&lt;br/>&lt;/t>&lt;/head>

**Comment by kosloot** [comment]
Hmm,
I assume that you run ucto on this example using this command:
ucto -Lnld --inputclass=default -F voorbeeld_NoSuchText.xml.txt 

This indeed yields:
ucto: no such text: s::textcontent(current)

I will look into this today

**Comment by JessedeDoes** [comment]
Actually 

ucto --textclass=default  --detectlanguages nld,fra,deu,eng,lat voorbeeld_NoSuchText.xml,

but that should not make a difference, I suppose

Thanks!

**Comment by kosloot** [comment]
No, the problem is related to the <br/> inside the text, combined with the dot.
I reduces to offensive file already to:
```<?xml version="1.0" encoding="UTF-8"?>
<FoLiA xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://ilk.uvt.nl/folia" xml:id="HuygensING-vandam-1-1_27426103-4e01-4d0c-8450-0dd83efa2bd3" generator="libfolia-v1.10" version="0.8.0">
  <metadata type="native">
    <annotations>
      <part-annotation annotatortype="auto" set="unknown"/>
      <division-annotation annotatortype="auto" set="unknown"/>
    </annotations>
  </metadata>
  <text xml:id="TEI.1">
    <part xml:id="TEI.1.text.1.front.1" class="frontmatter">
      <br newpage="yes" pagenr="1"/>
      <div xml:id="TEI.1.text.1.front.1.div1.1" class="div1">
<head xml:id="TEI.1.text.1.front.1.div1.4.head.1"><t class="default">Op.<br/></t></head>
      </div>
     </part>
   </text>
</FoLiA>```

And get the same error still

**Comment by JessedeDoes** [comment]
The problem disappears when you remove the break before the &lt;t> closing tag

&lt;head xml:id="TEI.1.text.1.front.1.div1.4.head.1">&lt;t class="default">Op.&lt;br/>&lt;/t>&lt;/head> 

does work

**Comment by kosloot** [comment]
Yeah, that was  clear. It is related to https://github.com/LanguageMachines/ucto/issues/25
as described there we will revert ucto to a non-break-detection state.
(already in Git)

**Comment by JessedeDoes** [comment]
Will I get this version (with non-break-detection) if I reinstall LaMachine, bootstrapping with the 'dev' argument?

**Comment by proycon** [comment]
Yes (no need to reinstall from scratch either, just run ``lamachine-update.sh`` within your virtualenv, it rebootstraps itself)

**Comment by JessedeDoes** [comment]
Toch nog een probleempje:
In de volgende p gaat het on de tokens dependeert en 1.

          &lt;p xml:id="TEI.1.text.1.body.1.div1.1.div2.1.div3.7.p.1" class="p">
              &lt;t class="default">&lt;t-style class="italic">Een nadere beschryvingh van de sydeteelt in en omtrent de landen&lt;/t-style> &lt;br/> &lt;t-style class="italic">van Cassimabasar , mitsgaders ’t gene daaraan, en aan ’t verhaspelen,&lt;/t-style> &lt;br/> &lt;t-style class="italic">dependeert&lt;/t-style> &lt;t-style class="superscript">1).&lt;/t-style>&lt;/t>
              &lt;lang class="nld" set="http://raw.github.com/proycon/folia/master/setdefinitions/iso639_3.foliaset"/>
            &lt;/p>


(lamachine)[does@vm10757 tei2folia]$ foliavalidator voorbeeld_NoSuchText.tokenized.xml 
TEXT VALIDATION ERROR: Text for Paragraph, ID TEI.1.text.1.body.1.div1.1.div2.1.div3.7.p.1, class default, is inconsistent: expected (after normalization): 'Een nadere beschryvingh van de sydeteelt in en omtrent de landen van Cassimabasar , mitsgaders ’t gene daaraan, en aan ’t verhaspelen, dependeert1).', got (after normalization): 'Een nadere beschryvingh van de sydeteelt in en omtrent de landen van Cassimabasar , mitsgaders ’t gene daaraan, en aan ’t verhaspelen, dependeert 1).'
WARNING: there were 1 text validation errors but these are currently not counted toward the full validation result (use -t for strict text validation)
Validated successfully: voorbeeld_NoSuchText.tokenized.xml

Inderdaad zijn dependeert en 1 aan elkaar geplakt bij het tokenizeren:
            
            &lt;w xml:id="TEI.1.text.1.body.1.div1.1.div2.1.div3.7.p.1.s.1.w.25" class="STRING-NUMBER" set="tokconfig-nld" space="no">
              &lt;t class="default">dependeert1&lt;/t>
            &lt;/w>

**Comment by proycon** [comment]
Dat lijkt me een rare tokeniser bug inderdaad, hij zou in principe niks aan elkaar moet plakken wat gescheiden is!

**Comment by kosloot** [comment]
Met recent ucto zie ik dit probleem niet opduiken.
Mocht het toch nog wel zo zijn , dan graag een voorbeeld document sturen.

Mijn testdoc:
[voorbeeld_NoSuchText.xml.txt](https://github.com/LanguageMachines/ucto/files/1384666/voorbeeld_NoSuchText.xml.txt)
 
Na ucto:
[voorbeeld_NoSuchText.tokenized.xml.txt](https://github.com/LanguageMachines/ucto/files/1384667/voorbeeld_NoSuchText.tokenized.xml.txt)

**Comment by JessedeDoes** [comment]
Sorry! Ik had voorbeeld_NoSuchText moeten aanpassen zodat hij het laatste probleem bevat.
Hierbij:

[voorbeeld_v2_NoSuchText.tokenized.xml.txt](https://github.com/LanguageMachines/ucto/files/1406542/voorbeeld_v2_NoSuchText.tokenized.xml.txt)
[voorbeeld_v2_NoSuchText.xml.txt](https://github.com/LanguageMachines/ucto/files/1406543/voorbeeld_v2_NoSuchText.xml.txt)

**Comment by JessedeDoes** [comment]
Alweer sorry! Zie dat je het probleem erin gezet had. Ga Lamachine weer updaten en kijk dan weer.

**Comment by kosloot** [comment]
Graag, want ik kan het niet meer reproduceren

**Comment by JessedeDoes** [comment]
Gaat na update alweer een stuk beter!

In de Van Dam collectie nog 1 probleempje:

 <p xml:id="TEI.1.text.1.body.1.div1.1.div2.21.div3.3.p.315" class="p">
              <t class="default">3 den schryver en twee kocx<br/> 16 dito’s tot ’t dragen der schen-</t>
              <lang class="deu"/>
            </p>
Geeft VALIDATION ERROR on full parse by library (stage 2/2), in Voorbeelden/voorbeeld_NoSuchText.tokenized.xml
ParseError: FoLiA exception in handling of <div> @ line 62: [InconsistentText] Text for Paragraph, ID TEI.1.text.1.body.1.div1.1.div2.21.div3.3.p.315, class default, is inconsistent: expected (after normalization): '3 den schryver en twee kocx 16 **dito ’s** tot ’t dragen der schen-', got (after normalization): '3 den schryver en twee kocx 16 **dito’s** tot ’t dragen der schen-'

Interessant: dit probleem treedt niet op als de taal (zoals eigenlijk zou moeten) op "nld" staat. Zit dus mogelijk in de tokconfig voor Duits?
[voorbeeld_3.xml.txt](https://github.com/LanguageMachines/ucto/files/1406975/voorbeeld_3.xml.txt)

**Comment by kosloot** [comment]
Dit is inderdaad een probleem in ucto data met de regels voor Duits.

Die zijn in de steentijd door Maarten gemaakt, dus ik hoop dat hij het oplost.
Te testen met de zin: "16 dito’s"
Nederlands:
```ucto -Lnld bug1.txt 
ucto: inputfile = bug1.txt
ucto: outputfile = 
ucto:tokconfig-nld: version=0.2
16 dito’s <utt> 
```

Duits:
```ucto -Ldeu bug1.txt 
ucto: inputfile = bug1.txt
ucto: outputfile = 
ucto:tokconfig-deu: version=0.2
16 dito ’s <utt> 
```
In het Duits slaat de SUFFIX regel toe, die 's afsplitst 
In het Nederlands wordt dit door de WORD-WITHSUFFIX regel bij elkaar gehouden.

**Comment by kosloot** [comment]
Hmm, nog even goed nadenkend:
Gebruik van --inputclass en --outputclass lijkt inderdaad wel een oplossing en ook wel een goed idee™, maar ik denk nu toch wel dat dit een bug is.
De gegenereerde FoLiA  voor Nederland bevat:
```
        <w xml:id="untitleddoc.p.1.s.1.w.1" class="NUMBER">
          <t>16</t>
        </w>
        <w xml:id="untitleddoc.p.1.s.1.w.2" class="WORD-WITHSUFFIX">
          <t>dito’s</t>
        </w>

```
En voor Duits:
```
      <s xml:id="untitleddoc.p.1.s.1">
        <w xml:id="untitleddoc.p.1.s.1.w.1" class="NUMBER">
          <t>16</t>
        </w>
        <w xml:id="untitleddoc.p.1.s.1.w.2" class="SUFFIX">
          <t>dito</t>
        </w>
        <w xml:id="untitleddoc.p.1.s.1.w.3" class="SUFFIX">
          <t>’s</t>
        </w>
      </s>
```
Duits heeft andere regels, maar het probleem is denk ik dat het tweede woord een attribuut space="no" moet krijgen!

Dat is mogelijk een ucto software probleem.

Maar helaas is er nog iets mis.
Als ik aan de zin  `16 dito's` een punt toevoeg `16 dito's.` dan krijg je voor Nederlands:
```
        <w xml:id="untitleddoc.p.1.s.1.w.1" class="NUMBER">
          <t>16</t>
        </w>
        <w xml:id="untitleddoc.p.1.s.1.w.2" class="WORD" space="no">
          <t>dito</t>
        </w>
        <w xml:id="untitleddoc.p.1.s.1.w.3" class="WORD-TOKEN" space="no">
          <t>’s</t>
        </w>
        <w xml:id="untitleddoc.p.1.s.1.w.4" class="PUNCTUATION">
          <t>.</t>
        </w>
```

en voor Duits:
```     <s xml:id="untitleddoc.p.1.s.1">
        <w xml:id="untitleddoc.p.1.s.1.w.1" class="NUMBER">
          <t>16</t>
        </w>
        <w xml:id="untitleddoc.p.1.s.1.w.2" class="SUFFIX" space="no">
          <t>dito</t>
        </w>
        <w xml:id="untitleddoc.p.1.s.1.w.3" class="SUFFIX" space="no">
          <t>’s</t>
        </w>
        <w xml:id="untitleddoc.p.1.s.1.w.4" class="PUNCTUATION">
          <t>.</t>
        </w>
```
Dus in het Nederlands wordt de WORD_WITHSUFFIX regel dan niet meer toegepast, en in het Duits wordt ineens space'"no" WEL toegevoegd. Spookachtig :{
Dit moet verder uitgezocht.

**Comment by JessedeDoes** [comment]
OK, ik wacht nog even af. Volgens mij is dit het enige probleem dat nog openstaat voor deze Nederlab-oplevering.

Als het nodig is kan ik de bestanden dus altijd validerend afleveren als input en outputclass verschillend zijn.

Bedankt!

**Comment by kosloot** [comment]
Ok, het probleem met de missende space="no"  lijkt opgelost. staat in Git
Problemen met UCTO regels en volgorde zijn van secundair belang.
Ik denk dat @JessedeDoes nu verder kan.

**Comment by kosloot** [comment]
Door een kleine aanpassing in uctodata (in tokconfig-nld) blijft ook de WORD-WITHSUFFIX nu bij elkaar.

**Comment by JessedeDoes** [comment]
Alle bestanden van deze batch komen er nu netjes doorheen.

Bedankt!!
