### ISSUE TITLE
Update debian package for ucto v0.14

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/ucto#36]

**Comment by proycon** [comment]
Updated on alioth

@kosloot: Please verify no ABI breakage from v0.9.6 to v0.9.8?

**Comment by kosloot** [comment]
ABI breakage was very likely. Bumped the .so version to 3.0.0

**Comment by proycon** [comment]
Ready on alioth, awaiting the rest prior to notification to debian sponsors

**Comment by proycon** [comment]
Oops, have to redo because of #38

**Comment by proycon** [comment]
Ready on alioth again

**Comment by proycon** [comment]
Process feedback from sponsor

**Comment by proycon** [comment]
@kosloot (@joostvb-gh?): The debian packaging currently fails on your install-data-hook (https://github.com/LanguageMachines/ucto/blob/master/config/Makefile.am#L7):

```
make[4]: Entering directory '/home/proycon/debian_packaging/ucto/config'                                                                                                                                                                                      
rm -f /usr/share/ucto/textcat.cfg                                                                                                                                                                                                                             
ln -s /usr/share/ucto/textcat_normal.cfg /usr/share/ucto/textcat.cfg                                                                                                                                                                                          
ln: failed to create symbolic link '/usr/share/ucto/textcat.cfg': Permission denied 
```

My guess is debian doesn't appreciate the package attempting to write directly to the target filesystem. Fyi, I am building without sudo.

**Comment by proycon** [comment]
ok, that seems to work, I'm adding a patch to the debian build so we don't need to rerelease because of this.
