### ISSUE TITLE
Abbreviations at the end of sentence not handled correctly

### ISSUE THREAD

**Issue by mhkuu** [LanguageMachines/ucto#4]
In line with issue #3, abbreviations at the end of a sentence seem not to be handled correctly, some examples follow. This might be harder to fix than the previous issue; as it's not obvious when an abbreviation really closes the sentence...

`De beurzen stegen met 3 Pct. Dat was een prima resultaat.`
`Met GitHub kan je issues taggen, pull requests mergen, e.d. Dat is super!`

**Comment by kosloot** [comment]
Fixing this is almost impossible.
as such, case of an abbreviation, followed by an upper-case word are easy to detect. Solving these examples.
De beurzen stegen met 3 Pct. <utt> Dat was een prima resultaat . <utt>
Met GitHub kan je issues taggen , pull requests mergen , e.d. <utt> Dat is super ! <utt> 

BUT
This will also split quite common constructions like:
George W. Bush  ==> George W. <utt> Bush
and
Dr. Bernard ==> Dr. <utt> Bernard

This is undesirable.
