### ISSUE TITLE
enable alternative search paths for uctodata

### ISSUE THREAD

**Issue by kosloot** [LanguageMachines/ucto#44]
Not all configurations allow installing uctodata stuff in $datadir/ucto (notably MacOSX)
where $datadir is something like $prefix/share
The alternative would be to install the ucto datafiles in $datadir/uctodata (that IS possible @fbkarsdorp ?)
ucto could then use a search path: first $datadir/ucto, and then $datadir/uctodata

Is this an option to try?

**Comment by fbkarsdorp** [comment]
That's possible, indeed. It's only a problem when installing through homebrew because of its protected built environment. By default, the data packages will be installed in `prefix=/usr/local/Cellar/uctodata/` and subsequently symlinked to `/usr/local/opt/uctodata/`

Is that something you can work with, @kosloot?

**Comment by kosloot** [comment]
I added some code in GIT to enable this. @fbkarsdorp can you test this without a new release?
I could send you a .tar.gz file

**Comment by fbkarsdorp** [comment]
Sure. Perhaps it's a good idea to add an option to the Brew Formulas allowing daredevils to brew from HEAD?

**Comment by kosloot** [comment]
Don't now if brewing from GIT is possible. the tarball is NOT in git, for sure/
Adding it here
[ucto-0.13.tar.gz](https://github.com/LanguageMachines/ucto/files/1747962/ucto-0.13.tar.gz)

**Comment by proycon** [comment]
Not sure if such a dare-devil option in homebrew is worth it; for what it's worth, LaMachine already offers a development installation path that pulls everything straight from git master (without homebrew even).

**Comment by kosloot** [comment]
@fbkarsdorp Were you able to test the for-mentioned tarball?

**Comment by kosloot** [comment]
this option was rather cumbersome.
It is now solved in the autoconfigure step. And seems to work well.
