### ISSUE TITLE
Install target breaks: ln: /usr/local/share/ucto/textcat.cfg: Permission denied

### ISSUE THREAD

**Issue by yurivict** [LanguageMachines/ucto#59]
```
gmake  install-data-hook
gmake[4]: Entering directory '/usr/ports/textproc/ucto/work/ucto-0.14/config'
rm -f /usr/local/share/ucto/textcat.cfg
ln -s /usr/local/share/ucto/textcat_normal.cfg /usr/local/share/ucto/textcat.cfg
ln: /usr/local/share/ucto/textcat.cfg: Permission denied
gmake[4]: *** [Makefile:527: install-data-hook] Error 1
```

'install' target should operate only on files under the directory $(DISTDIR)$(PREFIX).
Everything else isn't writable.

**Comment by yurivict** [comment]
This patch solves this problem:
```
--- config/Makefile.am.orig     2018-12-08 03:11:07 UTC
+++ config/Makefile.am
@@ -7,7 +7,7 @@ EXTRA_DIST = $(config_DATA)
 install-data-hook:
        rm -f $(configdir)/textcat.cfg
 if OLD_LM
-       $(LN_S) $(configdir)/textcat_alt.cfg $(configdir)/textcat.cfg
+       cd $(DESTDIR)$(configdir) && $(LN_S) textcat_alt.cfg textcat.cfg
 else
-       $(LN_S) $(configdir)/textcat_normal.cfg $(configdir)/textcat.cfg
+       cd $(DESTDIR)$(configdir) && $(LN_S) textcat_normal.cfg textcat.cfg
 endif
```

**Comment by proycon** [comment]
I earlier already ran into this same issue during debian packaging (#36) as well and committed fix 3d23bb5ea203686b6629ad2d8b372d9dabbde2bd .

**Comment by proycon** [comment]
But that commit didn't make it into a release yet, I used a small patch for debian as well, but perhaps we should just do a release.

**Comment by yurivict** [comment]
This is exactly the patch that I applied in the FreeBSD port.

**Comment by kosloot** [comment]
A bug-fix release seems appropriate. Will do that later this week.

**Comment by kosloot** [comment]
v014.1 which includes this patch is released:
 https://github.com/LanguageMachines/ucto/releases/tag/v0.14.1

**Comment by kosloot** [comment]
I assume this is solved now. Closing

**Comment by cdfa** [comment]
I got the same error in `v0.14-1` today.
However, I ran into a different error before: https://pastebin.com/6LAJKUyq
Then I installed `libexttextcat  3.4.5-1`, but got the link error.
Inspecting my file system `/usr/share/ucto/textcat_normal.cfg` doesn't exist.

```
> uname -a
Linux colin-laptop 4.19.23-1-MANJARO #1 SMP PREEMPT Fri Feb 15 21:27:33 UTC 2019 x86_64 GNU/Linux
```

**Comment by proycon** [comment]
Were you using the ucto package from the Arch User Repository? I see that one was still on 0.14 instead of 0.14.1 (!= 0.14-1). I just updated the AUR package so if you give it another try it hopefully works.

**Comment by cdfa** [comment]
Ah, my mistake. O thought they were the same version. Will try soon.

**Comment by cdfa** [comment]
It worked. Thanks for the quick response!
