### ISSUE TITLE
installing issue on Mac OS

### ISSUE THREAD

**Issue by alabrashJr** [LanguageMachines/ucto#61]
Hello everyone, 
I need help, I'm trying to install ucto on my mac but am getting the following error, 
![image](https://user-images.githubusercontent.com/9295206/50285490-5ffeef00-046d-11e9-83a1-37e9a4b9edec.png)
I tried to find anything through google but I could not. 

BR

**Comment by proycon** [comment]
The procedure you started is for compiling ucto from source, which is quite a technical process.
We suggest you use [LaMachine](https://proycon.github.io/LaMachine/) instead.

**Comment by alabrashJr** [comment]
@proycon thanks for your fast kindly replay. 
BR v
