### ISSUE TITLE
ucto should never create Words without an ID

### ISSUE THREAD

**Issue by kosloot** [LanguageMachines/ucto#66]
for the following example, ucto generated NO id's for the words.
This might be harmful, e.g. when Frog needs word id's to assign wrefs.
Input:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="folia.xsl"?>
<FoLiA xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://ilk.uvt.nl/folia" xml:id="test" generator="libfolia-v0.14" version="1.5">
  <metadata type="native">
    <annotations>
    </annotations>
  </metadata>
  <text xml:id="test.text">
    <div>
      <s>
	<t>Dit niet!</t>
      </s>
    </div>
  </text>
</FoLiA>
```

output:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="folia.xsl"?>
<FoLiA xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://ilk.uvt.nl/folia" xml:id="test" generator="libfolia-v1.16" version="1.5">
  <metadata type="native">
    <annotations>
      <token-annotation annotator="ucto" annotatortype="auto" datetime="2019-02-05T14:39:12" set="tokconfig-nld"/>
    </annotations>
    <meta id="language">nld</meta>
  </metadata>
  <text xml:id="test.text">
    <div>
      <s>
        <t>Dit niet!</t>
        <w class="WORD">
          <t>Dit</t>
        </w>
        <w class="WORD" space="no">
          <t>niet</t>
        </w>
        <w class="PUNCTUATION">
          <t>!</t>
        </w>
      </s>
    </div>
  </text>
</FoLiA>
```

Desired is auto-generation of id's.

NOTE: when the `<s>` layer is omitted, this works already OK

**Comment by kosloot** [comment]
This is partly fixed. Whenever the Word is connected to a node with an ID or with any (grand-)parent with an ID it will get a correct ID. 
Only problem left: FoLiA documents without an ID even on the '<text>' level.

**Comment by proycon** [comment]
It's fair enough to make an ID on the text level a prerequisite for ucto, even though FoLiA technically allows the text body to be ID-less.

**Comment by kosloot** [comment]
Agreed, but again: There is no guarantee that ALL documents in the wild conform to this rule.
If we add this restriction to Ucto, it, or Frog may throw, and leave the users clueless

**Comment by kosloot** [comment]
Having an ID is obligatory now, for both Ucto and Frog
