### ISSUE TITLE
file iso639_3.foliaset is missing

### ISSUE THREAD

**Issue by a-tsioh** [LanguageMachines/ucto#67]
"http://raw.github.com/proycon/folia/master/setdefinitions/iso639_3.foliaset" points to a 404
(and it prevents foliadocserve to accept uploads through FLAT, I'm not fully sure this is the right repository to report a bug)

**Comment by proycon** [comment]
Good point, I think foliadocserve and FLAT are a bit too strict in this regard. It would be better if they warn the user about missing set definitions, rather than fail to load a document completely. I'll implement the necessary changes for the upcoming release.

**Comment by proycon** [comment]
I added this set now.
