### ISSUE TITLE
Rerunning ucto on already tokenized FoLiA

### ISSUE THREAD

**Issue by kosloot** [LanguageMachines/ucto#68]
Now we have added provenance data, we can easily see if ucto has already been performed on incoming FoLiA.
If so, I assume that performing full tokenisation is NOT a wise plan. It might change the number of words or even sentences. 
We cannot cope with that. We could bail out with an error, but that is to harsh.
The best we can do at the moment is to inform the user about the problem and just output the incoming document AS IS as the result.
I have implemented this strategy and plan to include it in the upcoming FoliA2.0 release,
@proycon any comments on this?

**Comment by proycon** [comment]
If tokenisation has already been performed (and not necessarily by ucto but by any tool), then ucto should indeed not tokenise it again. Let's just assume that in such cases the entire document has been tokenised, (although technically there could be untokenised parts which ucto could still process). Quitting with either an error or a warning (and the document as is) sounds good to me. Just take care not to add any declarations or provenance data if you ucto does nothing with the document.

**Comment by kosloot** [comment]
Yes indeed. Although a partly "tokenized" document can be handled sometimes (e.g. when only paragraphs or sentences are available.) In that case no ucr\to provenance should be present, but maybe provenance from other tools. Or just old-style token-annotation declarations.
It is possible to handle most of these cases. I hope....
You are right that when "ignoring" a second ucto run, de document should remain untouched.
At the moment there is still a small problem in the current implementation regarding text-annotation declarations. I will fix that prior to the release.

**Comment by kosloot** [comment]
assume this is fixed, as we don't have a counter example and 2.0 is released

**Comment by kosloot** [comment]
There is is "small" problem which we didn't notice before:

When running ucto again again on an already tokenized document, what do we do with the parameters ``inputclass`` and ``outputclass``? Leaving such a document "untouched" means that NO output with text in class ``outputclass`` is produced.
Is that desirable? Or should we copy all inputclass text to outputclass?
This gets more urgent when ``textredundancy=full`` is specified, as that will fail when no text in ``outputclass`` is available

Here is a simple example:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<FoLiA xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://ilk.uvt.nl/folia" xml:id="bug" generator="libfolia-v2.15" version="2.5.1">
  <metadata type="native">
    <annotations>
      <paragraph-annotation>
        <annotator processor="FoLiA-page.1"/>
      </paragraph-annotation>
      <text-annotation set="https://raw.githubusercontent.com/proycon/folia/master/setdefinitions/text.foliaset.ttl"/>
      <sentence-annotation>
        <annotator processor="FoLiA-page.1"/>
      </sentence-annotation>
      <token-annotation>
        <annotator processor="FoLiA-page.1"/>
      </token-annotation>
    </annotations>
    <provenance>
      <processor xml:id="FoLiA-page.1" begindatetime="2023-04-12T08:35:19" command="FoLiA-page --trusttokens -O out/page" folia_version="2.5.1" host="kobus" name="FoLiA-page" user="sloot" version="0.21">
        <processor xml:id="FoLiA-page.1.generator" folia_version="2.5.1" name="libfolia" type="generator" version="2.15"/>
      </processor>
    </provenance>
  </metadata>
  <text xml:id="text">
    <p xml:id="text.p">
      <s xml:id="text.p.s">
        <t class="OCR">Quellen</t>
        <w xml:id="p.text.w">
          <t class="OCR">Quellen</t>
        </w>
      </s>
    </p>
  </text>
</FoLiA>
```
running ```ucto -Ldeu --inputclass=OCR  -F ucto.xml``` works, more or less as expected

but running ```ucto -Ldeu --inputclass=OCR --textredundancy=full -F ucto.xml``` yields:
``ucto: no such text: s::text_content(current)``

Which is unfortunate.
Not sure what to do?  Emit an error? Copy the text to the outputclass?

**Comment by kosloot** [comment]
@proycon I added 2 patches to ucto:
1.  Catch the "no such text" exception, and warn about having a problem assigning ``outputclass``, due to already fully tokenized ``inputclass'`` text.
2.   Added a ``--copyclass`` option, to assign a text copy of ``inputclass`` text to ``outputclass``

This seams to be sound. But comment is welcome

**Comment by proycon** [comment]
The ``--copyclass`` solution seems like a decent way to cover this, I agree.  The "no such text" exception is nasty indeed and will throw people off, the warning you implemented now looks good to me and at least suggests some ways out (lke setting --copyclass). 

It all remains a rather edge-case scenario of course with quite some complexity involved, but as we've seen, it does occur...
