### ISSUE TITLE
separate dat from code

### ISSUE THREAD

**Issue by kosloot** [LanguageMachines/ucto#7]
It would be convenient to have the config data in a separate package, just like frogdata for frog.
This would allow for updates in the rules/languages without disturbing other software depending on Ucto

**Comment by proycon** [comment]
I'm not really convinced this is necessary. The configurations are very small, a separate package seems overkill and harder to maintain. We can also just update them and raise the ucto version number without any API/ABI breakage right?

**Comment by kosloot** [comment]
every 'make install' triggers a unneeded recompilation of all Ucto dependencies, notably Frog,
because in will refresh all .h files.
Also a simple rule-chance in a language can then be deployed without a full Ucto release.

**Comment by kosloot** [comment]
released
