### ISSUE TITLE
ucto breaks on empty FoLiA comment

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/ucto#71]
This is just a very minor issue and no priority, just noting it here for the record. Ucto breaks on an empty FoLiA comment: ``<comment></comment>`` with:

```
ucto: value attribute is required for comment
```

However, both validators do not stumble over this. It's of course arguable whether an empty comment is a valid comment, but let's not be too picky about it.

**Comment by kosloot** [comment]
libfolia was more picky on emtpy `<comment>` and `<desc>` nodes then foliapy.
I relaxed this a bit, which should solve this.
