### ISSUE TITLE
ucto sometimes misses out on the <t> for <p> 

### ISSUE THREAD

**Issue by martinreynaert** [LanguageMachines/ucto#84]
Hi,

I attach a small archive with the command line used in the README.txtx, the input file and two output versions, one for nld, the other for nld-historical. 

Ucto on occasion does not give the ``<t>`` element for a ``<p>``, as in the following example from the nld-historical output:
```xml
<p xml:id="DODOENS_VOL1.p.51">
      <s xml:id="DODOENS_VOL1.p.51.s.1">
        <t>2 V Tsap van die wilde Ruyte met huenich/ wijn/ sap van Fenkel/ ende galle van een hinne wel ghemenght scerpt het tghesichte ende neempt alle vlecken ende scellen van den ooghen.</t>
```

Thanks for looking into this!

Martin
[UCTOmissingParagraphs.tar.gz](https://github.com/LanguageMachines/ucto/files/6975350/UCTOmissingParagraphs.tar.gz)

**Comment by kosloot** [comment]
I updated your text, as a lot was invisible :)
The text on the ``<p>`` should be present, as you use the ``--textredundancy=full`` option.
This is a bug indeed.

**Comment by kosloot** [comment]
@martinreynaert As far as I can see, only the text on the last paragraph was missing.
I fixed that. Please test

**Comment by kosloot** [comment]
assume it is OK now
