### ISSUE TITLE
IDs in UCTO in concert with tei2folia

### ISSUE THREAD

**Issue by martinreynaert** [LanguageMachines/ucto#85]
UCTO vs. tei2folia

About element IDs.

-i in tei2folia only allows one to specify one wants an ID to be created for every element. Far as I can see, this is then called 'undefined' (regardless of whether created for every element or not).

--id in UCTO allows one to specify a name for the ID, e.g. based on the input file name.

The latter, however, cannot undo the 'undefined' created by the former, it seems.

I have *many* files I need to convert from TEI from FoLiA. Before running them through SPACY, I want to tokenize and sentence split the paragraphs with UCTO.

Please do note I did run tei2folia without the -i parameter. I can deliver a sample input TEI file (through another channel only) and the actual command lines used.

In what we do, unique IDs for definitely the `<p>` elements are vital.

I would either like tei2folia have the IDs named *or* UCTO undo the 'undefined' and set a proper name for the IDs. I have a preference for the latter as this might also serve for FoLiA produced by convertors other than tei2folia.

Thanks!

MRE

**Comment by proycon** [comment]
`tei2folia` indeed doesn't allow you to specify an ID because it attempts to extract the ID from the TEI document and uses that. Only when it can't find an ID in the TEI document  does it fall back to `undefined`. Do your TEI documents have anything like `//tei:publicationStmt/tei:idno`? We might need to tweak tei2folia a bit if it doesn't recognize it yet.

**Comment by kosloot** [comment]
On the point of changing the ID's in hindsight:

This is a hell of a job: That would also mean checking and changing internal references.
AND, what happens when afFoLiA file is external to another one?

**Comment by martinreynaert** [comment]
Given the ramifications involved, I understand it would be a bad idea to try and solve this in Ucto.

Thanks also for the pointer to the idno tei-element! My input files had these, but I removed them before: they contain isbn-numbers, therefore give invalid xml and rightly broke tei2folia. I now replace them in a preprocessing step in which other issues are also dealt with by the base form of the file name and this gives the desired result in running Ucto.

This issue can be considered resolved and closed.
