### ISSUE TITLE
Setting -m in container does not supress punctuation-based sentence splitting

### ISSUE THREAD

**Issue by pirolen** [LanguageMachines/ucto#95]
I'm passing a plain text file, one sentence per line.
`docker run -t -i proycon/ucto -L rus -m` etc. however still does punctuation-based sentence splitting :-/

**Comment by proycon** [comment]
Indeed, this looks like a regression bug. Reproduces on ucto v0.30 and v0.31.

**Comment by kosloot** [comment]
hmm....
Interesting enough, NONE of tests in the testsuite tests this option, so this regression is never detected.
Will have a look into it

**Comment by kosloot** [comment]
OK, I did some research, and this regression is introduced in v0.15 (sic)  It dates may 15, 2019
Quite embarrassing .

**Comment by kosloot** [comment]
A fix is now in Git. All seems to work now. 
NOTE: I'm quite sure you will need ``-n`` together with ``-m`` to enjoy the full flavor.

Side-note: this fix revealed a failing test for Frog too. Solved that on the fly
